// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "widget": {
      name: "widget",
      description: "",
      type: "registry:wigggle",
      registryDependencies: undefined,
      files: ["registry/default/wigggle/widget.tsx"],
      component: React.lazy(() => import("@/registry/default/wigggle/widget.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/default/lib/utils.ts"],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "basic-example-widget": {
      name: "basic-example-widget",
      description: "",
      type: "registry:example",
      registryDependencies: [""],
      files: ["registry/default/example/basic-example-widget.tsx"],
      component: React.lazy(() => import("@/registry/default/example/basic-example-widget.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "custom-styles-widget": {
      name: "custom-styles-widget",
      description: "",
      type: "registry:example",
      registryDependencies: [""],
      files: ["registry/default/example/custom-styles-widget.tsx"],
      component: React.lazy(() => import("@/registry/default/example/custom-styles-widget.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "weather-default": {
      name: "weather-default",
      description: "",
      type: "registry:example",
      registryDependencies: ["weather"],
      files: ["registry/default/docs/weather/weather-default.tsx"],
      component: React.lazy(() => import("@/registry/default/docs/weather/weather-default.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "weather-rectangle": {
      name: "weather-rectangle",
      description: "",
      type: "registry:example",
      registryDependencies: ["weather"],
      files: ["registry/default/docs/weather/weather-rectangle.tsx"],
      component: React.lazy(() => import("@/registry/default/docs/weather/weather-rectangle.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "weather-large": {
      name: "weather-large",
      description: "",
      type: "registry:example",
      registryDependencies: ["weather"],
      files: ["registry/default/docs/weather/weather-large.tsx"],
      component: React.lazy(() => import("@/registry/default/docs/weather/weather-large.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "clock-default": {
      name: "clock-default",
      description: "",
      type: "registry:example",
      registryDependencies: ["clock"],
      files: ["registry/default/docs/clock/clock-default.tsx"],
      component: React.lazy(() => import("@/registry/default/docs/clock/clock-default.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "clock-rectangle": {
      name: "clock-rectangle",
      description: "",
      type: "registry:example",
      registryDependencies: ["clock"],
      files: ["registry/default/docs/clock/clock-rectangle.tsx"],
      component: React.lazy(() => import("@/registry/default/docs/clock/clock-rectangle.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "clock-large": {
      name: "clock-large",
      description: "",
      type: "registry:example",
      registryDependencies: ["clock"],
      files: ["registry/default/docs/clock/clock-large.tsx"],
      component: React.lazy(() => import("@/registry/default/docs/clock/clock-large.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "calendar-default": {
      name: "calendar-default",
      description: "",
      type: "registry:example",
      registryDependencies: ["calendar"],
      files: ["registry/default/docs/calendar/calendar-default.tsx"],
      component: React.lazy(() => import("@/registry/default/docs/calendar/calendar-default.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "calendar-rectangle": {
      name: "calendar-rectangle",
      description: "",
      type: "registry:example",
      registryDependencies: ["calendar"],
      files: ["registry/default/docs/calendar/calendar-rectangle.tsx"],
      component: React.lazy(() => import("@/registry/default/docs/calendar/calendar-rectangle.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "calendar-large": {
      name: "calendar-large",
      description: "",
      type: "registry:example",
      registryDependencies: ["calendar"],
      files: ["registry/default/docs/calendar/calendar-large.tsx"],
      component: React.lazy(() => import("@/registry/default/docs/calendar/calendar-large.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "use-mobile": {
      name: "use-mobile",
      description: "",
      type: "registry:hook",
      registryDependencies: undefined,
      files: ["registry/default/hooks/use-mobile.ts"],
      component: React.lazy(() => import("@/registry/default/hooks/use-mobile.ts")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "use-toast": {
      name: "use-toast",
      description: "",
      type: "registry:hook",
      registryDependencies: undefined,
      files: ["registry/default/hooks/use-toast.ts"],
      component: React.lazy(() => import("@/registry/default/hooks/use-toast.ts")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
  },
}
