// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "weather": {
      name: "weather",
      description: "",
      type: "registry:wigggle",
      registryDependencies: undefined,
      files: ["registry/default/wigggle/weather.tsx"],
      component: React.lazy(() => import("@/registry/default/wigggle/weather.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/default/lib/utils.ts"],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "weather-default": {
      name: "weather-default",
      description: "",
      type: "registry:example",
      registryDependencies: ["weather"],
      files: ["registry/default/example/weather-default.tsx"],
      component: React.lazy(() => import("@/registry/default/example/weather-default.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "weather-rectangle": {
      name: "weather-rectangle",
      description: "",
      type: "registry:example",
      registryDependencies: ["weather"],
      files: ["registry/default/example/weather-rectangle.tsx"],
      component: React.lazy(() => import("@/registry/default/example/weather-rectangle.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "weather-large": {
      name: "weather-large",
      description: "",
      type: "registry:example",
      registryDependencies: ["weather"],
      files: ["registry/default/example/weather-large.tsx"],
      component: React.lazy(() => import("@/registry/default/example/weather-large.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "use-mobile": {
      name: "use-mobile",
      description: "",
      type: "registry:hook",
      registryDependencies: undefined,
      files: ["registry/default/hooks/use-mobile.ts"],
      component: React.lazy(() => import("@/registry/default/hooks/use-mobile.ts")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "use-toast": {
      name: "use-toast",
      description: "",
      type: "registry:hook",
      registryDependencies: undefined,
      files: ["registry/default/hooks/use-toast.ts"],
      component: React.lazy(() => import("@/registry/default/hooks/use-toast.ts")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
  },
}
